/**
 * Writes the current package version into `playground/src/version.ts` so the
 * playground can display it without a runtime `fetch` (which would not resolve
 * on a static deploy). Run as the first step of the `playground:*` tasks.
 */
import denoJson from "../deno.json" with { type: "json" };

const out = `// AUTO-GENERATED by scripts/gen-playground-version.ts — do not edit.\n` +
	`export const VERSION = ${JSON.stringify(denoJson.version)};\n`;

await Deno.writeTextFile(new URL("../playground/src/version.ts", import.meta.url), out);
console.log(`playground version → ${denoJson.version}`);
